FROM maven:3.8.6-openjdk-18 AS build
WORKDIR /usr/src/app 
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD

COPY . .

RUN echo "The SPRING_DATASOURCE_USERNAME is:" $SPRING_DATASOURCE_USERNAME

RUN mvn install:install-file \
     -Dfile=.mvn/wrapper/maven-wrapper.jar \
     -DgroupId=dev.ApiApplication \
     -DartifactId=api \
     -Dversion=1.0 \
     -Dpackaging=jar \
     -DgeneratePom=true \
     -DSPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
     -DSPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
     -q \
     -X

ENV SPRING_DATASOURCE_USERNAME ${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD ${SPRING_DATASOURCE_PASSWORD}

EXPOSE 8080
EXPOSE 80

ENTRYPOINT mvn -DSPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} -DSPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} spring-boot:run

